![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [155]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Schools with the best math results
best_math = schools['average_math'] >= 800 * 80 / 100
best_math_schools = schools.loc[best_math, ['school_name','average_math']].sort_values(by='average_math', ascending=False)

# Top 10 performing schools
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']
top_10_schools = schools[['school_name','total_SAT']].sort_values(by='total_SAT', ascending=False).head(10)
print(top_10_schools)

# Borough that has the largest standard deviation
group_by_borough = schools.groupby('borough').agg(num_schools=('school_name','count'), average_SAT=('total_SAT','mean'), std_SAT=('total_SAT','std'))
print(group_by_borough.head())

largest_std_dev = group_by_borough[group_by_borough['std_SAT'] == group_by_borough['std_SAT'].max()].round(2)
print(largest_std_dev)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889
               num_schools  average_SAT     std_SAT
borough
Bronx                   98  1202.724490  150.393901
Brooklyn               109  1230.256881  154.868427
Manhattan               89  1340.134831  230.294140
Queens                  69  1345.478261  195.252899
Staten Island           10  1439.000000  222.303596
           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29